"""add entity extraction tables

Revision ID: fec28b5b115d
Revises: 20251229_llm_validated
Create Date: 2026-01-15 19:59:21.023257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fec28b5b115d'
down_revision: Union[str, None] = '20251229_llm_validated'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Pre-create enum types with IF NOT EXISTS to handle databases where
    # these types were already created outside of Alembic (e.g., via create_all)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE entitytypeenum AS ENUM ('PERSON', 'ORGANIZATION', 'COMPANY', 'LOCATION', 'OTHER');
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE entityroleenum AS ENUM (
                'GOVERNMENT_OFFICIAL', 'DIPLOMAT', 'BUSINESS_LEADER', 'CULTURAL_FIGURE',
                'MILITARY_OFFICIAL', 'ACADEMIC', 'MEDIA_FIGURE', 'CIVIL_SOCIETY',
                'IMPLEMENTING_ORGANIZATION', 'FUNDING_ORGANIZATION', 'RECIPIENT_INSTITUTION',
                'INFRASTRUCTURE_PROJECT', 'VENUE', 'OTHER'
            );
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
    """)

    op.create_table('canonical_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('master_entity_id', sa.UUID(), nullable=True),
    sa.Column('llm_validated', sa.Boolean(), nullable=False),
    sa.Column('llm_validated_at', sa.DateTime(), nullable=True),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORGANIZATION', 'COMPANY', 'LOCATION', 'OTHER', name='entitytypeenum', create_type=False), nullable=False),
    sa.Column('initiating_country', sa.Text(), nullable=False),
    sa.Column('primary_role', sa.Enum('GOVERNMENT_OFFICIAL', 'DIPLOMAT', 'BUSINESS_LEADER', 'CULTURAL_FIGURE', 'MILITARY_OFFICIAL', 'ACADEMIC', 'MEDIA_FIGURE', 'CIVIL_SOCIETY', 'IMPLEMENTING_ORGANIZATION', 'FUNDING_ORGANIZATION', 'RECIPIENT_INSTITUTION', 'INFRASTRUCTURE_PROJECT', 'VENUE', 'OTHER', name='entityroleenum', create_type=False), nullable=True),
    sa.Column('country_affiliations', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('alternative_names', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('first_mention_date', sa.Date(), nullable=False),
    sa.Column('last_mention_date', sa.Date(), nullable=False),
    sa.Column('total_mention_days', sa.Integer(), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('primary_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('associated_events', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('entity_description', sa.Text(), nullable=True),
    sa.Column('key_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_entity_id'], ['canonical_entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canonical_entity_country_dates', 'canonical_entities', ['initiating_country', 'first_mention_date', 'last_mention_date'], unique=False)
    op.create_index('ix_canonical_entity_llm_validated', 'canonical_entities', ['llm_validated'], unique=False)
    op.create_index('ix_canonical_entity_master', 'canonical_entities', ['master_entity_id'], unique=False)
    op.create_index('ix_canonical_entity_name', 'canonical_entities', ['canonical_name'], unique=False)
    op.create_index('ix_canonical_entity_role', 'canonical_entities', ['primary_role'], unique=False)
    op.create_index('ix_canonical_entity_type', 'canonical_entities', ['entity_type'], unique=False)
    op.create_table('entity_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('initiating_country', sa.Text(), nullable=False),
    sa.Column('cluster_date', sa.Date(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORGANIZATION', 'COMPANY', 'LOCATION', 'OTHER', name='entitytypeenum', create_type=False), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('entity_names', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('doc_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('cluster_size', sa.Integer(), nullable=False),
    sa.Column('is_noise', sa.Boolean(), nullable=False),
    sa.Column('centroid_embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('representative_name', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('llm_deconflicted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('refined_clusters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initiating_country', 'cluster_date', 'entity_type', 'batch_number', 'cluster_id', name='uq_entity_cluster')
    )
    op.create_index('ix_entity_cluster_country_date_type', 'entity_clusters', ['initiating_country', 'cluster_date', 'entity_type'], unique=False)
    op.create_index('ix_entity_cluster_processed', 'entity_clusters', ['processed', 'llm_deconflicted'], unique=False)
    op.create_table('daily_entity_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_entity_id', sa.UUID(), nullable=False),
    sa.Column('initiating_country', sa.Text(), nullable=False),
    sa.Column('mention_date', sa.Date(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('primary_role_this_day', sa.Text(), nullable=True),
    sa.Column('activities_this_day', sa.Text(), nullable=True),
    sa.Column('doc_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('associated_event_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['canonical_entity_id'], ['canonical_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_entity_id', 'mention_date', name='uq_daily_entity_mention')
    )
    op.create_index('ix_daily_entity_mention_country_date', 'daily_entity_mentions', ['initiating_country', 'mention_date'], unique=False)
    op.create_index('ix_daily_entity_mention_date', 'daily_entity_mentions', ['mention_date'], unique=False)
    op.create_table('raw_entities',
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORGANIZATION', 'COMPANY', 'LOCATION', 'OTHER', name='entitytypeenum', create_type=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('country_affiliation', sa.Text(), nullable=True),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ),
    sa.PrimaryKeyConstraint('doc_id', 'entity_name', 'entity_type')
    )
    op.create_index('ix_raw_entity_country', 'raw_entities', ['country_affiliation'], unique=False)
    op.create_index('ix_raw_entity_doc_date', 'raw_entities', ['doc_id'], unique=False)
    op.create_index('ix_raw_entity_type', 'raw_entities', ['entity_type'], unique=False)
    # Drop old entity tables if they exist (with CASCADE to handle dependencies)
    op.execute('DROP TABLE IF EXISTS document_entities CASCADE')
    op.execute('DROP TABLE IF EXISTS entities CASCADE')
    op.execute('DROP TABLE IF EXISTS langchain_pg_embedding CASCADE')
    op.execute('DROP TABLE IF EXISTS langchain_pg_collection CASCADE')
    op.execute('DROP TABLE IF EXISTS entity_extraction_runs CASCADE')
    op.alter_column('bilateral_category_summaries', 'material_score_histogram',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('canonical_events', 'total_mention_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('canonical_events', 'total_articles',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('canonical_events', 'story_phase',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('canonical_events', 'days_since_last_mention',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('canonical_events', 'unique_sources',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('canonical_events', 'source_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('canonical_events', 'peak_daily_article_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('canonical_events', 'key_facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('canonical_events', 'alternative_names',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('canonical_events', 'primary_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('canonical_events', 'primary_recipients',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('country_category_summaries', 'material_score_histogram',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('daily_event_mentions', 'article_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_event_mentions', 'consolidated_headline',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('daily_event_mentions', 'source_names',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('daily_event_mentions', 'source_diversity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('daily_event_mentions', 'mention_context',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('daily_event_mentions', 'news_intensity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('daily_event_mentions', 'doc_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    # Drop and recreate entity_relationships with new schema
    op.execute('DROP TABLE IF EXISTS entity_relationships CASCADE')
    op.create_table('entity_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_from_id', sa.UUID(), nullable=False),
    sa.Column('entity_to_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('co_occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_co_occurrence', sa.Date(), nullable=False),
    sa.Column('last_co_occurrence', sa.Date(), nullable=False),
    sa.Column('primary_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationship_description', sa.Text(), nullable=True),
    sa.Column('source_doc_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_from_id'], ['canonical_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_to_id'], ['canonical_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_from_id', 'entity_to_id', 'relationship_type', name='uq_entity_relationship'),
    sa.CheckConstraint('entity_from_id != entity_to_id', name='ck_no_self_relationship')
    )
    op.create_index('ix_entity_rel_from', 'entity_relationships', ['entity_from_id'], unique=False)
    op.create_index('ix_entity_rel_to', 'entity_relationships', ['entity_to_id'], unique=False)
    op.create_index('ix_entity_rel_type', 'entity_relationships', ['relationship_type'], unique=False)
    op.create_index('ix_entity_rel_dates', 'entity_relationships', ['first_co_occurrence', 'last_co_occurrence'], unique=False)
    op.alter_column('event_summaries', 'material_score',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_summaries', 'material_score',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    op.add_column('entity_relationships', sa.Column('avg_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('sample_descriptions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('document_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('sample_doc_ids', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('observation_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('source_entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('first_observed', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('last_observed', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('entity_relationships', sa.Column('total_value_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'entity_relationships', type_='foreignkey')
    op.drop_constraint(None, 'entity_relationships', type_='foreignkey')
    op.create_foreign_key('entity_relationships_source_entity_id_fkey', 'entity_relationships', 'entities', ['source_entity_id'], ['id'])
    op.create_foreign_key('entity_relationships_target_entity_id_fkey', 'entity_relationships', 'entities', ['target_entity_id'], ['id'])
    op.drop_index('ix_entity_rel_type', table_name='entity_relationships')
    op.drop_index('ix_entity_rel_to', table_name='entity_relationships')
    op.drop_index('ix_entity_rel_from', table_name='entity_relationships')
    op.drop_index('ix_entity_rel_dates', table_name='entity_relationships')
    op.drop_constraint('uq_entity_relationship', 'entity_relationships', type_='unique')
    op.create_unique_constraint('uq_entity_relationship', 'entity_relationships', ['source_entity_id', 'target_entity_id', 'relationship_type'])
    op.create_index('ix_relationship_type', 'entity_relationships', ['relationship_type'], unique=False)
    op.create_index('ix_relationship_target', 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_index('ix_relationship_source', 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index('ix_relationship_dates', 'entity_relationships', ['first_observed', 'last_observed'], unique=False)
    op.alter_column('entity_relationships', 'relationship_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('entity_relationships', 'source_doc_ids')
    op.drop_column('entity_relationships', 'relationship_description')
    op.drop_column('entity_relationships', 'primary_categories')
    op.drop_column('entity_relationships', 'last_co_occurrence')
    op.drop_column('entity_relationships', 'first_co_occurrence')
    op.drop_column('entity_relationships', 'co_occurrence_count')
    op.drop_column('entity_relationships', 'entity_to_id')
    op.drop_column('entity_relationships', 'entity_from_id')
    op.alter_column('daily_event_mentions', 'doc_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('daily_event_mentions', 'news_intensity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('daily_event_mentions', 'mention_context',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('daily_event_mentions', 'source_diversity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('daily_event_mentions', 'source_names',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('daily_event_mentions', 'consolidated_headline',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('daily_event_mentions', 'article_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('country_category_summaries', 'material_score_histogram',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('canonical_events', 'primary_recipients',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('canonical_events', 'primary_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('canonical_events', 'alternative_names',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('canonical_events', 'key_facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('canonical_events', 'peak_daily_article_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('canonical_events', 'source_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('canonical_events', 'unique_sources',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('canonical_events', 'days_since_last_mention',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('canonical_events', 'story_phase',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('canonical_events', 'total_articles',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('canonical_events', 'total_mention_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bilateral_category_summaries', 'material_score_histogram',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_table('entity_extraction_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('initiating_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('documents_processed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entities_extracted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relationships_extracted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('errors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entity_extraction_runs_pkey')
    )
    op.create_table('langchain_pg_collection',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('langchain_pg_embedding',
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name='langchain_pg_embedding_collection_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name='langchain_pg_embedding_pkey')
    )
    op.create_table('entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('canonical_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('first_seen_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_seen_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mention_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primary_topics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('primary_roles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['entities.id'], name='entities_parent_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_index('ix_entity_mention_count', 'entities', ['mention_count'], unique=False)
    op.create_index('ix_entity_country', 'entities', ['country'], unique=False)
    op.create_index('ix_entity_canonical_name', 'entities', ['canonical_name'], unique=False)
    op.create_index('ix_entity_aliases', 'entities', ['aliases'], unique=False, postgresql_using='gin')
    op.create_table('document_entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doc_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('topic_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('role_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_in_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization_in_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('extraction_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], name='document_entities_doc_id_fkey'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name='document_entities_entity_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_entities_pkey'),
    sa.UniqueConstraint('doc_id', 'entity_id', name='uq_document_entity_doc_entity')
    )
    op.create_index('ix_doc_entity_topic', 'document_entities', ['topic_label'], unique=False)
    op.create_index('ix_doc_entity_side', 'document_entities', ['side'], unique=False)
    op.create_index('ix_doc_entity_role', 'document_entities', ['role_label'], unique=False)
    op.create_index('ix_doc_entity_entity_id', 'document_entities', ['entity_id'], unique=False)
    op.create_index('ix_doc_entity_doc_id', 'document_entities', ['doc_id'], unique=False)
    op.drop_index('ix_raw_entity_type', table_name='raw_entities')
    op.drop_index('ix_raw_entity_doc_date', table_name='raw_entities')
    op.drop_index('ix_raw_entity_country', table_name='raw_entities')
    op.drop_table('raw_entities')
    op.drop_index('ix_daily_entity_mention_date', table_name='daily_entity_mentions')
    op.drop_index('ix_daily_entity_mention_country_date', table_name='daily_entity_mentions')
    op.drop_table('daily_entity_mentions')
    op.drop_index('ix_entity_cluster_processed', table_name='entity_clusters')
    op.drop_index('ix_entity_cluster_country_date_type', table_name='entity_clusters')
    op.drop_table('entity_clusters')
    op.drop_index('ix_canonical_entity_type', table_name='canonical_entities')
    op.drop_index('ix_canonical_entity_role', table_name='canonical_entities')
    op.drop_index('ix_canonical_entity_name', table_name='canonical_entities')
    op.drop_index('ix_canonical_entity_master', table_name='canonical_entities')
    op.drop_index('ix_canonical_entity_llm_validated', table_name='canonical_entities')
    op.drop_index('ix_canonical_entity_country_dates', table_name='canonical_entities')
    op.drop_table('canonical_entities')
    # ### end Alembic commands ###
